CUDA_VISIBLE_DEVICES=0 python ctg/model/rl/ppo/ppo.py \
    --model_name_or_path ctg/ckpts/sft/sft_gpt2-med_06092024/checkpoint-5600 \
    --sft_model_path ctg/ckpts/sft/sft_gpt2-med_06092024/checkpoint-5600 \
    --reward_model_path ctg/ckpts/rm/rm_gpt2-med_06092024/checkpoint-450 \
    --output_dir ctg/ckpts/rl/rl_ppo/rl_ppo_gpt2-med_09092024 \
    --exp_name ctg/ckpts/rl/rl_ppo/rl_ppo_gpt2-med_09092024 \
    --learning_rate 1.41e-5 \
    --num_ppo_epochs 1 \
    --num_mini_batches 1 \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 4 \
    --total_episodes 10000 \
    --non_eos_penalty \
    --stop_token eos \
    --response_length 32 \
    --local_rollout_forward_batch_size 8 \
    --save_total_limit 1 \
    --load_best_model_at_end False \
    --eval_strategy steps \
    --save_strategy steps \
    --eval_steps 50 \
    --save_steps 50 \