CUDA_VISIBLE_DEVICES=0 python ctg/model/sft/sft.py \
    --model_name_or_path gpt2 \
    --report_to wandb \
    --learning_rate 1.41e-5 \
    --adam_epsilon 1e-08 \
    --max_seq_length 256 \
    --num_train_epochs 2\
    --per_device_train_batch_size 64 \
    --per_device_eval_batch_size 64 \
    --eval_strategy steps \
    --save_strategy steps \
    --save_steps 100 \
    --save_total_limit 1 \
    --load_best_model_at_end True \
    --warmup_ratio 0.1 \
    --output_dir ctg/ckpts/sft/sft_ctg_31082024 \
    --logging_steps 100 \
    --gradient_checkpointing \
